### ISSUE TITLE
What about if the K in myGemm4 cannot be devided by TS or WIDTH?

### ISSUE THREAD

**Issue by dolmens** [CNugteren/myGEMM#1]
say the K is 7\*7\*3=147, TS=32, WIDTH=4

**Comment by CNugteren** [comment]
Then it doesn't work indeed. The myGEMM tutorial is meant to illustrate GEMM kernel development and optimisation, but it doesn't support all use-cases. In a production GEMM implementation (e.g. in [CLBlast](https://github.com/CNugteren/CLBlast)) you'll have to handle these cases, either with an if-statement or by pre-padding the input to make sure you meet the requirements of the kernel.

**Comment by dolmens** [comment]
Ok.
