### ISSUE TITLE
Wrong Output if the Matrix Dimensions are not of the order of Tile sizes

### ISSUE THREAD

**Issue by abhi1212** [CNugteren/myGEMM#2]
Hello All,

I just checked the correctness of some kernels, and it appears to me that if the  Matrix Dimensions are not of the order of Tile sizes then you get wrong output.
Also, I did not see any bound checkings on any kernel.
Can anyone help me with this?
@CNugteren

**Comment by CNugteren** [comment]
Indeed. The myGEMM tutorial is meant to illustrate GEMM kernel development and optimisation, but it doesn't support all use-cases. In a production GEMM implementation (e.g. in [CLBlast](https://github.com/CNugteren/CLBlast)) you'll have to handle these cases, either with an if-statement or by pre-padding the input to make sure you meet the requirements of the kernel.
