### ISSUE TITLE
Row-Major - Kernel 3

### ISSUE THREAD

**Issue by skn123** [CNugteren/myGEMM#3]
Suppose if we want to use Row-major matrices in kernels.cl what would need to changed (especially in Kernel 3) ?

**Comment by CNugteren** [comment]
I hink thats the same as pre-transposing, right? Would just swapping A and B work? For a full working implementation you can always check out the CLBlast library of course.

**Comment by iperov** [comment]
@CNugteren is col-major impl faster than row-major ?

**Comment by CNugteren** [comment]
There is no yes/no answer to this question. In both cases you will run the same GEMM kernel, the only thing you need to do is pre-transpose one of the matrices, in both cases, and post-transpose one of the matrices in one case. It depends if you care about this transposing as well. And even if you do care, the transpose is a memory-bound O(n^2) operation, whereas GEMM itself is compute-bound O(n^3). So for large enough values of `n` and on most devices you won't notice the speed-impact of this pre/post transposing.

See also [here](https://cnugteren.github.io/tutorial/pages/page2.html) and the second paragraph in section 3.2 [here](https://arxiv.org/pdf/1705.05249.pdf).

**Comment by iperov** [comment]
Interesting, I just swapped arguments a,b -> b,a to col-major gemm, now it works like row-major without transposes.

**Comment by iperov** [comment]
I think gemm11 is the best. Speed is only 74% slower than tensorflow matmul, but it is very universal.
It does not use local memory, thus work fine on CPU devices without local workgroups.

**Comment by CNugteren** [comment]
> Interesting, I just swapped arguments a,b -> b,a to col-major gemm, now it works like row-major without transposes.

I think this is in line with what I was trying to say above :-)

> I think gemm11 is the best. Speed is only 74% slower than tensorflow matmul, but it is very universal.
It does not use local memory, thus work fine on CPU devices without local workgroups.

This code is for a tutorial to learn how to optimize the code. If you really care about speed and want to use this in a production environment, you should use https://github.com/CNugteren/CLBlast, a library based on the kernels in this tutorial.

**Comment by iperov** [comment]
thanks, but it is very redundant, I like simpler things.

**Comment by iperov** [comment]
> I think this is in line with what I was trying to say above :-)

swap arguments is not the same as transpose arguments :D

**Comment by CNugteren** [comment]
What I mean is that if you want to compute A * B, and you use the 'myGEMM' kernel, you assume A is pre-transposed. Thus, the kernel actually computes the operation A^T * B. Then if you switch from row to col-major you can swap the arguments indeed as it will now compute A * B^T. It is all just a matter of definition and whether or not you care about pre-transposing and care about obtaining transposed output. You can see this in the [CLBlast source code](https://github.com/CNugteren/CLBlast/blob/master/src/routines/level3/xgemm.cpp#L171) where optional pre/post transpose kernels are being called conditionally based on [this comment and implementation](https://github.com/CNugteren/CLBlast/blob/master/src/routines/level3/xgemm.hpp#L91) which reads:

     // Computes whether or not the matrices are transposed in memory. This is based on their layout
     // (row or column-major) and whether or not they are requested to be pre-transposed. Note
     // that the Xgemm kernel expects either matrices A and C (in case of row-major) or B (in case of
     // col-major) to be transposed, so transposing requirements are not the same as whether or not
     // the matrix is actually transposed in memory.
