### ISSUE TITLE
VS 2015 compiler?

### ISSUE THREAD

**Issue by evdem** [CNugteren/myGEMM#4]
sorry, I can't compile "extra" example in VS 2015. I get errors in "time.h" routines:
```
	struct timeval Tvalue;
	struct timezone dummy;
...
	gettimeofday(&Tvalue, &dummy);
	double starttime = (double)Tvalue.tv_sec + 1.0e-6*((double)Tvalue.tv_usec);
...
	double endtime = (double)Tvalue.tv_sec + 1.0e-6*((double)Tvalue.tv_usec);
```
"Tvalue, dummy, gettimeofday" are highlighted

**Comment by CNugteren** [comment]
Sorry I can't help you out with Visual Studio support. This is demo code, so it might not work everywhere properly. But you can have a look at it and/or try to make it run in your own framework if you want.

If you want production-level code that does compile with VS 2015, you can have a look at [CLBlast](https://github.com/CNugteren/CLBlast).
