### ISSUE TITLE
follow the step, and the result became slow

### ISSUE THREAD

**Issue by yxdragon** [CNugteren/myGEMM#5]
Hi, I follow your guide, and use pyopencl test. But I find it became more and more slow:
I test a 1024^2 array to dot.
mygemm1: 120 ms
mygemm2: 250 ms
mygemm3: 3500 ms
and I did not go on...

Can you give me some tips? 

here is the code. upload as a txt file.

[dot_test.txt](https://github.com/CNugteren/myGEMM/files/4431918/dot_test.txt)

**Comment by CNugteren** [comment]
Sorry I can't go to deep into your particular problem, but at high level you could:
1) Try to run with the code supplied in this repository and see what you get then.
2) Make sure you are measuring time properly, e.g. run multiple times, exclude the first (it might be compiling your kernel what you are measuring, etc.).
