### ISSUE TITLE
Did you try indirect GEMM ?

### ISSUE THREAD

**Issue by iperov** [CNugteren/myGEMM#7]
as explained in this paper https://arxiv.org/pdf/1907.02129.pdf

**Comment by CNugteren** [comment]
I didn't go through the full paper but briefly skimmed it, but I believe what this is is basically im2col and GEMM merged together in one kernel to perform convolution? If that is indeed what this is about, then the answer is yes, it is implemented in [CLBlast](https://github.com/CNugteren/CLBlast). See [this thread](https://github.com/CNugteren/CLBlast/issues/267) for the discussion on it (feature request from a date before this paper was released though) and [here](https://github.com/CNugteren/CLBlast/blob/master/doc/details_conv.md) for the documentation of the CONVGEMM routine.
