### ISSUE TITLE
Matrix multiplication optimization problem

### ISSUE THREAD

**Issue by xiexijin** [CNugteren/myGEMM#8]
I would like to ask some questions. When I was optimizing matrix multiplication operation, I encountered the following problems when dividing matrix into blocks:  
I want to implement matrix multiplication optimization on the neural network (without calling library function), but I find that the matrix dimension size of each layer in the network changes dynamically, and the size of the matrix changes greatly, so it is difficult to determine the size of the block. Should WE dynamically adjust the size of the block according to the size of the matrix?  Another problem is that the size of the matrix dimension appears to be 169 (13*13), so the block size should be 13. How can thread optimization be performed in this case?

**Comment by CNugteren** [comment]
> but I find that the matrix dimension size of each layer in the network changes dynamically, and the size of the matrix changes greatly, so it is difficult to determine the size of the block. Should WE dynamically adjust the size of the block according to the size of the matrix?

Indeed, that is not a trivial problem. The [CLBlast library](https://github.com/CNugteren/CLBlast/) can tune for different sizes, but to support all at best speed is not possible of course. You can take a few block sizes that are good for most of the layers you are using in your neural network. There are other possibilities: you can use machine learning to guess a good size based on some earlier benchmarks (see e.g. the [ISAAC paper](https://dl.acm.org/doi/10.1145/3126908.3126939) or you can do a few runs live while running your networks and after a few training/inference runs find the optimal parameters. The [CLBlast paper](https://arxiv.org/abs/1705.05249) also has a few thoughts on this.

> Another problem is that the size of the matrix dimension appears to be 169 (13*13), so the block size should be 13.

You can run a pre/post-processing kernel to pad those matrices with zeros and then run e.g. with a 16x16 block size. This is what CLBlast also does in some cases. In others it runs what is called a 'direct' GEMM kernel, see [the CLBlast docs](https://github.com/CNugteren/CLBlast/blob/master/doc/details_gemm.md) or code for more info.

**Comment by xiexijin** [comment]
Thank you for your answer.
